In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import regex as re
import pickle as pkl

In [2]:
df = pd.read_csv("data/df_cleaned.csv")
df.head()

,event_id,player_id_home,name_home,seed_home,aces_home,backhand_errors_home,backhand_unforced_errors_home,backhand_winners_home,breakpoints_won_home,double_faults_home,...,win_home,avg_set_length,avg_game_length,avg_points_per_game,match_length,rs_home,rs_away,avg_set_diff,avg_set_games,sets
0,sr:sport_event:42023445,sr:competitor:66968,"Kudermetova, Veronika",0,14,13,8,9,1,1,...,True,50.983333,4.433333,6.913043,101.966667,12.0,101.0,1.500000,11.500000,2
1,sr:sport_event:42023447,sr:competitor:41355,"Bogdan, Ana",1,6,12,7,7,3,2,...,True,72.141667,5.549359,6.769231,144.283333,61.0,15.0,1.000000,13.000000,2
2,sr:sport_event:42023449,sr:competitor:256547,"Parks, Alycia",1,5,8,17,3,4,5,...,True,50.866667,5.354386,7.210526,101.733333,47.0,87.0,2.500000,9.500000,2
3,sr:sport_event:42023459,sr:competitor:99131,"Bucsa, Cristina",1,6,34,15,10,6,4,...,True,54.772222,5.134896,7.187500,164.316667,77.0,70.0,0.666667,10.666667,3
4,sr:sport_event:42023461,sr:competitor:44834,"Pegula, Jessica",0,3,20,14,11,5,3,...,True,46.783333,4.678333,6.600000,140.350000,4.0,44.0,2.000000,10.000000,3

Combining similar variables (winners and errors) ..?

In [3]:
# errors = []
# unforced_errors = []
# winners = []
# for col in df.columns:
#     if "errors" in col:
#         er = re.match(r"^(.+_errors)(_[a-z]+)$", col).group(1) 
#         if "unforced" in col:
#             if er not in unforced_errors:
#                 unforced_errors.append(er)
#         else:
#             if er not in errors:
#                 errors.append(er)
#     elif "winners" in col:
#         win = re.match(r"^(.+_winners)(_[a-z]+)$", col).group(1) 
#         if win not in winners:
#             winners.append(win)

# print(errors)
# print(unforced_errors)
# print(winners)

In [ ]:
# # add double faults to errors
# errors.append("double_faults")

In [4]:
# for who in ['_home','_away']:
#     df["errors"+who] = df[[err+who for err in errors]].sum(axis=1)
#     df["unforced_errors"+who] = df[[err+who for err in unforced_errors]].sum(axis=1)
#     df['winners'+who] = df[[win+who for win in winners]].sum(axis=1)
#     df = df.drop(columns = [err+who for err in errors]+[err+who for err in unforced_errors]+[win+who for win in winners])

In [5]:
df.head()

,event_id,player_id_home,name_home,seed_home,aces_home,backhand_errors_home,backhand_unforced_errors_home,backhand_winners_home,breakpoints_won_home,double_faults_home,...,win_home,avg_set_length,avg_game_length,avg_points_per_game,match_length,rs_home,rs_away,avg_set_diff,avg_set_games,sets
0,sr:sport_event:42023445,sr:competitor:66968,"Kudermetova, Veronika",0,14,13,8,9,1,1,...,True,50.983333,4.433333,6.913043,101.966667,12.0,101.0,1.500000,11.500000,2
1,sr:sport_event:42023447,sr:competitor:41355,"Bogdan, Ana",1,6,12,7,7,3,2,...,True,72.141667,5.549359,6.769231,144.283333,61.0,15.0,1.000000,13.000000,2
2,sr:sport_event:42023449,sr:competitor:256547,"Parks, Alycia",1,5,8,17,3,4,5,...,True,50.866667,5.354386,7.210526,101.733333,47.0,87.0,2.500000,9.500000,2
3,sr:sport_event:42023459,sr:competitor:99131,"Bucsa, Cristina",1,6,34,15,10,6,4,...,True,54.772222,5.134896,7.187500,164.316667,77.0,70.0,0.666667,10.666667,3
4,sr:sport_event:42023461,sr:competitor:44834,"Pegula, Jessica",0,3,20,14,11,5,3,...,True,46.783333,4.678333,6.600000,140.350000,4.0,44.0,2.000000,10.000000,3

In [6]:
sorted(df.columns)

['aces_away',
 'aces_home',
 'avg_game_length',
 'avg_points_per_game',
 'avg_set_diff',
 'avg_set_games',
 'avg_set_length',
 'backhand_errors_away',
 'backhand_errors_home',
 'backhand_unforced_errors_away',
 'backhand_unforced_errors_home',
 'backhand_winners_away',
 'backhand_winners_home',
 'best_of',
 'breakpoints_won_away',
 'breakpoints_won_home',
 'competition',
 'date',
 'double_faults_away',
 'double_faults_home',
 'drop_shot_unforced_errors_away',
 'drop_shot_unforced_errors_home',
 'drop_shot_winners_away',
 'drop_shot_winners_home',
 'event_id',
 'first_serve_points_won_away',
 'first_serve_points_won_home',
 'first_serve_successful_away',
 'first_serve_successful_home',
 'forehand_errors_away',
 'forehand_errors_home',
 'forehand_unforced_errors_away',
 'forehand_unforced_errors_home',
 'forehand_winners_away',
 'forehand_winners_home',
 'games_won_away',
 'games_won_home',
 'groundstroke_errors_away',
 'groundstroke_errors_home',
 'groundstroke_unforced_errors_away',
 'groundstroke_unforced_errors_home',
 'groundstroke_winners_away',
 'groundstroke_winners_home',
 'lob_unforced_errors_away',
 'lob_unforced_errors_home',
 'lob_winners_away',
 'lob_winners_home',
 'match_length',
 'max_games_in_a_row_away',
 'max_games_in_a_row_home',
 'max_points_in_a_row_away',
 'max_points_in_a_row_home',
 'men',
 'name_away',
 'name_home',
 'overhead_stroke_errors_away',
 'overhead_stroke_errors_home',
 'overhead_stroke_unforced_errors_away',
 'overhead_stroke_unforced_errors_home',
 'overhead_stroke_winners_away',
 'overhead_stroke_winners_home',
 'player_id_away',
 'player_id_home',
 'points_won_away',
 'points_won_from_last_10_away',
 'points_won_from_last_10_home',
 'points_won_home',
 'return_errors_away',
 'return_errors_home',
 'return_winners_away',
 'return_winners_home',
 'round',
 'rs_away',
 'rs_home',
 'second_serve_points_won_away',
 'second_serve_points_won_home',
 'second_serve_successful_away',
 'second_serve_successful_home',
 'seed_away',
 'seed_home',
 'service_games_won_away',
 'service_games_won_home',
 'service_points_lost_away',
 'service_points_lost_home',
 'service_points_won_away',
 'service_points_won_home',
 'sets',
 'tiebreaks_won_away',
 'tiebreaks_won_home',
 'total_breakpoints_away',
 'total_breakpoints_home',
 'volley_unforced_errors_away',
 'volley_unforced_errors_home',
 'volley_winners_away',
 'volley_winners_home',
 'win_home']

In [7]:
context_vars = ["event_id","date","name_home","name_away","competition","player_id_home","player_id_away", "best_of","round"]
context = df[context_vars]

In [8]:
stats_df = df.drop(columns = context_vars)
stats_df.insert(0, "men", stats_df.pop("men"))
stats_df

,men,seed_home,aces_home,backhand_errors_home,backhand_unforced_errors_home,backhand_winners_home,breakpoints_won_home,double_faults_home,drop_shot_unforced_errors_home,drop_shot_winners_home,...,win_home,avg_set_length,avg_game_length,avg_points_per_game,match_length,rs_home,rs_away,avg_set_diff,avg_set_games,sets
0,False,0,14,13,8,9,1,1,0,0,...,True,50.983333,4.433333,6.913043,101.966667,12.0,101.0,1.500000,11.500000,2
1,False,1,6,12,7,7,3,2,0,0,...,True,72.141667,5.549359,6.769231,144.283333,61.0,15.0,1.000000,13.000000,2
2,False,1,5,8,17,3,4,5,0,0,...,True,50.866667,5.354386,7.210526,101.733333,47.0,87.0,2.500000,9.500000,2
3,False,1,6,34,15,10,6,4,0,0,...,True,54.772222,5.134896,7.187500,164.316667,77.0,70.0,0.666667,10.666667,3
4,False,0,3,20,14,11,5,3,0,0,...,True,46.783333,4.678333,6.600000,140.350000,4.0,44.0,2.000000,10.000000,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940,True,0,8,10,11,7,9,9,0,0,...,True,55.894444,5.782184,6.827586,167.683333,3.0,8.0,2.333333,9.666667,3
941,True,0,3,5,10,12,4,3,0,0,...,True,50.033333,5.559259,6.444444,150.100000,1.0,12.0,3.000000,9.000000,3
942,True,1,5,20,11,4,2,5,0,0,...,False,53.683333,5.368333,6.700000,161.050000,46.0,2.0,-2.666667,10.000000,3
943,True,0,0,25,14,12,1,0,0,0,...,False,49.737500,5.235526,6.894737,198.950000,1.0,3.0,-1.500000,9.500000,4
944,True,0,6,12,22,6,1,6,0,0,...,False,65.744444,6.362366,6.935484,197.233333,3.0,2.0,-2.333333,10.333333,3

In [9]:
#stats_df['avg_set_diff'] = abs(stats_df['avg_set_diff'])

In [10]:
overall_stats = []
specific_stats = set()
specific_stats_all = []
for col in stats_df.columns:
    if "home" not in col and "away" not in col:
        overall_stats.append(col)
    elif "home" in col:
        specific_stats.add(re.match(r"^(.*?)\_home",col).group(1))
        specific_stats_all.append(col)
    elif "away" in col:
        specific_stats.add(re.match(r"^(.*?)\_away",col).group(1))
        specific_stats_all.append(col)

In [21]:
with open('data/specific_stats.pkl', 'wb') as f:
    pkl.dump(specific_stats, f)

with open('data/overall_stats.pkl', 'wb') as f:
    pkl.dump(overall_stats, f)

In [18]:
specific_stats

{'aces',
 'backhand_errors',
 'backhand_unforced_errors',
 'backhand_winners',
 'breakpoints_won',
 'double_faults',
 'drop_shot_unforced_errors',
 'drop_shot_winners',
 'first_serve_points_won',
 'first_serve_successful',
 'forehand_errors',
 'forehand_unforced_errors',
 'forehand_winners',
 'games_won',
 'groundstroke_errors',
 'groundstroke_unforced_errors',
 'groundstroke_winners',
 'lob_unforced_errors',
 'lob_winners',
 'max_games_in_a_row',
 'max_points_in_a_row',
 'overhead_stroke_errors',
 'overhead_stroke_unforced_errors',
 'overhead_stroke_winners',
 'points_won',
 'points_won_from_last_10',
 'return_errors',
 'return_winners',
 'rs',
 'second_serve_points_won',
 'second_serve_successful',
 'seed',
 'service_games_won',
 'service_points_lost',
 'service_points_won',
 'tiebreaks_won',
 'total_breakpoints',
 'volley_unforced_errors',
 'volley_winners',
 'win'}

In [11]:
overall_stats
# Only match_length from this list needs to be 'normalized'

['men',
 'avg_set_length',
 'avg_game_length',
 'avg_points_per_game',
 'match_length',
 'avg_set_diff',
 'avg_set_games',
 'sets']

New feature?

In [12]:
# df['expected_win'] = (df['win'+h] & df['rs_diff']>0) | (~df['win'+h] & df['rs_diff']<0)

In [13]:
h = '_home'
a = '_away'

def both(col):
    return [col+h,col+a]

In [14]:
from itertools import chain
# Normalize by dividing by the number of sets played in a given match
to_normalize = list(specific_stats_all.copy())
not_to = both('rs')+both('max_games_in_a_row')+both('max_points_in_a_row')+both('seed')+both('win')
to_normalize = [x for x in to_normalize if x not in not_to]
to_normalize.append('match_length')
stats_df[to_normalize] = stats_df[to_normalize].div(df['sets'], axis=0)

In [15]:
stats_df

,men,seed_home,aces_home,backhand_errors_home,backhand_unforced_errors_home,backhand_winners_home,breakpoints_won_home,double_faults_home,drop_shot_unforced_errors_home,drop_shot_winners_home,...,win_home,avg_set_length,avg_game_length,avg_points_per_game,match_length,rs_home,rs_away,avg_set_diff,avg_set_games,sets
0,False,0,7.000000,6.500000,4.000000,4.500000,0.500000,0.500000,0.0,0.0,...,True,50.983333,4.433333,6.913043,50.983333,12.0,101.0,1.500000,11.500000,2
1,False,1,3.000000,6.000000,3.500000,3.500000,1.500000,1.000000,0.0,0.0,...,True,72.141667,5.549359,6.769231,72.141667,61.0,15.0,1.000000,13.000000,2
2,False,1,2.500000,4.000000,8.500000,1.500000,2.000000,2.500000,0.0,0.0,...,True,50.866667,5.354386,7.210526,50.866667,47.0,87.0,2.500000,9.500000,2
3,False,1,2.000000,11.333333,5.000000,3.333333,2.000000,1.333333,0.0,0.0,...,True,54.772222,5.134896,7.187500,54.772222,77.0,70.0,0.666667,10.666667,3
4,False,0,1.000000,6.666667,4.666667,3.666667,1.666667,1.000000,0.0,0.0,...,True,46.783333,4.678333,6.600000,46.783333,4.0,44.0,2.000000,10.000000,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940,True,0,2.666667,3.333333,3.666667,2.333333,3.000000,3.000000,0.0,0.0,...,True,55.894444,5.782184,6.827586,55.894444,3.0,8.0,2.333333,9.666667,3
941,True,0,1.000000,1.666667,3.333333,4.000000,1.333333,1.000000,0.0,0.0,...,True,50.033333,5.559259,6.444444,50.033333,1.0,12.0,3.000000,9.000000,3
942,True,1,1.666667,6.666667,3.666667,1.333333,0.666667,1.666667,0.0,0.0,...,False,53.683333,5.368333,6.700000,53.683333,46.0,2.0,-2.666667,10.000000,3
943,True,0,0.000000,6.250000,3.500000,3.000000,0.250000,0.000000,0.0,0.0,...,False,49.737500,5.235526,6.894737,49.737500,1.0,3.0,-1.500000,9.500000,4
944,True,0,2.000000,4.000000,7.333333,2.000000,0.333333,2.000000,0.0,0.0,...,False,65.744444,6.362366,6.935484,65.744444,3.0,2.0,-2.333333,10.333333,3

In [17]:
stats_df.to_csv('data/df_progress.csv')